# Version de développement : branche development de partiduo-dist (dépôts
# partiduo-* sur development). Installée dans son propre répertoire
# (lib/partiduo-devel, rc.d/partiduo_devel), elle cohabite avec partiduo-app.
DISTVERSION=	0.1.0.20261001
PKGNAMESUFFIX=	-devel

COMMENT=	Invoicing and accounting for small businesses (development version)

PARTIDUO_NAME=	partiduo-devel
PARTIDUO_RC=	partiduo_devel

MASTERDIR=	${.CURDIR}/../partiduo-app

.include "${MASTERDIR}/Makefile"
